djangotweet/djangotweet/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("tweetapp.urls")),
    path("",include("django.contrib.auth.urls"))

]

djangotweet/tweetapp/urls.py
from django.urls import path
from.import views

app_name="tweetapp"

urlpatterns = [
    path("",views.listtweet, name="listtweet"),
    path("addtweet/",views.addtweet, name="addtweet"),
    path("addtweetbyform",views.addtweetbyform,name="addtweetbyform"),
    path("addtweetbymodelform",views.addtweetbymodelform,name="addtweetbymodelform"),
    path("signup/" ,views.SignUpView.as_view() , name="signup"),
    path("deletetweet/<int:id>" ,views.deletetweet , name="deletetweet")
    
    
]

djangotweet/tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Tweet(models.Model):

    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    message=models.CharField(max_length=200)

    def __str__(self):
        return f" Tweet user:{self.username} message:{self.message} "   

djangotweet/tweetapp/forms.py
from django import forms 
from django.forms import ModelForm
from tweetapp.models import Tweet



class AddTweetForm(forms.Form):
    nickname_input=forms.CharField(label="Nickname",max_length=50)
    message_input=forms.CharField(label="Message",max_length=100,
                                  widget=forms.Textarea(attrs={"class":"tweetmessage"}))
    

class AddTweetModelForm(ModelForm):
    class Meta:
        model=Tweet
        fields=["username","message"]

djangotweet/tweetapp/views.py
from django.shortcuts import render,redirect
from.import models
from django.urls import reverse,reverse_lazy
from tweetapp.forms import AddTweetForm,AddTweetModelForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import CreateView






def listtweet(request):
    all_tweets=models.Tweet.objects.all()
    tweet_dict={"tweets":all_tweets}
    
    return render(request,"tweetapp/listtweet.html",context=tweet_dict)

@login_required(login_url="/login")
def addtweet(request):
     if request.POST:         
       
        
        message=request.POST["message"]
        
        
        models.Tweet.objects.create(username=request.user ,message=message)
         # secondway ---> models.Tweet.objects.create(nickname=nickaname,message=message),tweet=models.Tweet(nickname,message)  tweet.save()
       
        return redirect(reverse('tweetapp:listtweet'))
     else:
        return render(request, "tweetapp/addtweet.html")

def addtweetbyform(request):
    if request.POST:
        form=AddTweetForm(request.POST)
        if form.is_valid():
             nickname=form.cleaned_data["nickname_input"]
             message=form.cleaned_data["message_input"]
             tweet=models.Tweet(nickname,message)
             tweet.save()
             return redirect(reverse('tweetapp:listtweet'))
        
        
        else:
            print("error in form")
            return render(request,'tweetapp/addtweetbyform.html',context={"form":form})
    else:
        form=AddTweetForm()
        print("error in form")
        return render(request,'tweetapp/addtweetbyform.html',context={"form":form})

def addtweetbymodelform(request):
     if request.POST:
        form=AddTweetModelForm(request.POST)
        if form.is_valid():
             nickname=form.cleaned_data["nickname"]
             message=form.cleaned_data["message"]
             tweet=models.Tweet(nickname,message)
             tweet.save()
             return redirect(reverse('tweetapp:listtweet'))
        
        
        else:
            print("error in form")
            return render(request,'tweetapp/addtweetbymodelform.html',context={"form":form})
     
     else:
        form=AddTweetModelForm()
        return render(request,'tweetapp/addtweetbymodelform.html',context={"form":form})

@login_required
def deletetweet(request,id):
    tweet=models.Tweet.objects.get(pk=id)
    if request.user == tweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return redirect(reverse('tweetapp:listtweet'))






class SignUpView(CreateView):
    form_class=UserCreationForm
    success_url=reverse_lazy("login")
    template_name="registration/signup.html"

                        

                


    


        
        
       

        

               

    

     

djangotweet/templates/base.html
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>TweetApp</title>
    <link rel=" stylesheet" href= "{% static 'tweetapp/custom.css'%}">

 


</head>

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tweetapp:listtweet' %}">ÖzerMuskTweeter</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href= "{% url 'tweetapp:listtweet' %}">List</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweet' %}">Addtweet</a>
              </li>
              <!--
              <li class="nav-item">
                <a class="nav-link" href="{% url 'tweetapp:addtweetbyform' %}">Addtweetbyform</a>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'tweetapp:addtweetbymodelform' %}">AddtweetbyModelform</a>
                </li>
                
              </li>
              -->
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
              
              <li class="nav-item" style="padding-left: 800px;">
                <a class="nav-link" href="{% url 'tweetapp:signup' %}">Sign up</a>
              </li>
              <li class="nav-item" >
                <a class="nav-link" href="{% url 'logout' %}?next=/">Logout</a>
              </li>
            
            
            </ul>
           
          </div>
        </div>
    </nav>

    {% block content   %}
  

    



    {% endblock   %}
    
    

    
    
</body>
</html>

djangotweet/tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}


{% block content   %}

<form  action=" " method="POST">
  {%csrf_token%}
  <div class="container" style="width: 50%;">
       
        
        <div class="mb-3">
          <label for="message" class="form-label" name="nickname">Message</label>
          <input type="text" class="form-control" id="message" name="message">
        </div>
      
        <button type="submit" class="btn btn-primary">send tweet</button>

  </div>
  </form>


{% endblock   %}

djangotweet/tweetapp/templates/tweetapp/addtweetbyform.html
{% extends "base.html" %}
{%load static%}


{% block content   %}
<div  class="container tweetform">
        <form  action=" " method="POST" >
          {%csrf_token%}
          {%for field in form%}
          <div class="mb-3">
          {{field.label_tag}}
          {{field}}
        
           </div>


          
          
          
          
          {%endfor%}
          


          
            <button type="submit" class="btn btn-primary">send tweet</button>
          </form>

</div>
{% endblock   %}

djangotweet/tweetapp/templates/tweetapp/addtweetbymodelform.html
{% extends "base.html" %}
{%load static%}



{% block content   %}
<h2>Addtweetpageby ModelForm page</h2>

<div  class="container tweetform">
    <form  action=" " method="POST" >
      {%csrf_token%}
      {%for field in form%}
      <div class="mb-3">
      {{field.label_tag}}
      {{field}}
    
       </div>


      
      
      
      
      {%endfor%}
      


      
        <button type="submit" class="btn btn-primary">send tweet</button>
      </form>

</div>
       


{% endblock   %}

djangotweet/tweetapp/templates/tweetapp/listtweet.html
{%extends "base.html"%}


{% block content %}


    <div class="container" style="width: 50%;" >
         {% for tweet in tweets %}
        
         <div class="card" style="padding:10px;">
            
            <div class ="card-header" style="background-color: rgb(74, 74, 216);">
                <h5>{{tweet.username}}</h5>
            </div>
           
            <div class ="card-body">
                <h6><p class="card-text">{{tweet.message}} </p></h6>
            </div>
            {%if tweet.username == user %}

            <a href="{%url 'tweetapp:deletetweet' id=tweet.id %}" class="btn btn-danger">Delete</a>
            
            
            {% endif %}

                
             
        </div>
        {%endfor%}
    </div>


            
 





{% endblock   %}